name: 'translation_pipeline'
version: '1.0.0'
config-version: 2
profile: 'translation_pipeline'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  translation_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: view
